services:
  - type: web
    name: uniconnect-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://atharvap0369:feBgFMvtbSFUE2ty@cluster0.8czbvzr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: abhatyrahagc
      - key: EMAIL_USER
        value: abhayraj27052005@gmail.com
      - key: EMAIL_APP_PASSWORD
        value: eiwx enkn vnlb mjmj

  - type: static
    name: uniconnect-frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    env:
      - key: VITE_API_URL
        value: https://uniconnect-backend.onrender.com