services:
  - type: web
    name: uniconnect-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CORS_ORIGIN
        value: https://uniconnect-qs2s.onrender.com
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: "*"
      - path: /*
        name: Access-Control-Allow-Methods
        value: "GET, POST, PUT, DELETE, OPTIONS"
      - path: /*
        name: Access-Control-Allow-Headers
        value: "Origin, X-Requested-With, Content-Type, Accept, Authorization"
    disk:
      name: uploads
      mountPath: /opt/render/project/src/backend/uploads
      sizeGB: 1

  - type: static
    name: uniconnect-frontend
    buildCommand: cd frontend && npm install && npm run build
    publishDir: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://uniconnect-backend-zd5n.onrender.com